# Generated by Django 4.2.30 on 2026-05-01 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('active', 'Active'), ('finished', 'Finished')], default='draft', max_length=10)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_expeditions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expeditions',
            },
        ),
        migrations.CreateModel(
            name='ExpeditionMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('invited', 'Invited'), ('confirmed', 'Confirmed')], default='invited', max_length=10)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='expeditions.expedition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedition_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expedition_members',
                'unique_together': {('expedition', 'user')},
            },
        ),
    ]
